export default {
  1: require("../assets/topicIntro/presentSimple.html"),
  2: require("../assets/topicIntro/presentContinuous.html"),
  3: require("../assets/topicIntro/presentPerfect.html"),
  4: require("../assets/topicIntro/presentPerfectCont.html"),
  5: require("../assets/topicIntro/pastSimple.html"),
  6: require("../assets/topicIntro/pastContinuous.html"),
  7: require("../assets/topicIntro/pastPerfect.html"),
  8: require("../assets/topicIntro/pastPerfectCont.html"),
  9: require("../assets/topicIntro/futureSimple.html"),
  10: require("../assets/topicIntro/futureContinuous.html"),
  11: require("../assets/topicIntro/futurePerfect.html"),
  12: require("../assets/topicIntro/futurePerfectCont.html"),
  13: require("../assets/topicIntro/nouns.html"),
  14: require("../assets/topicIntro/pronoun.html"),
  15: require("../assets/topicIntro/adjective.html"),
};
