export default [
  {
    id: 391,
    quizId: 40,
    type: "multiple_choice",
    text: "'Which of the following is/are common nouns?' select all that apply.",
    options: [
      { id: "a", text: "Food" },
      { id: "b", text: "Eiffel Tower" },
      { id: "c", text: "City" },
      { id: "d", text: "Butterfly" },
    ],
    correctOptionId: ["a", "c", "d"],
    explanation: "Food, City, Butterfly",
  },
  {
    id: 392,
    quizId: 40,
    type: "multiple_choice",
    text: "Which of the following is/are proper nouns? Select all that apply.",
    options: [
      { id: "a", text: "Ocean" },
      { id: "b", text: "John Smith" },
      { id: "c", text: "Monday" },
      { id: "d", text: "Planet Earth" },
    ],
    correctOptionId: ["b", "c", "d"],
    explanation: "John Smith, Monday, Planet Earth",
  },
  {
    id: 393,
    quizId: 40,
    type: "multiple_choice",
    text: "Which of the following is/are concrete nouns? Select all that apply.",
    options: [
      { id: "a", text: "Love" },
      { id: "b", text: "Dog" },
      { id: "c", text: "Freedom" },
      { id: "d", text: "Table" },
    ],
    correctOptionId: ["b", "d"],
    explanation: "Dog, Table",
  },
  {
    id: 394,
    quizId: 40,
    type: "multiple_choice",
    text: "Which of the following is/are abstract nouns? Select all that apply.",
    options: [
      { id: "a", text: "Happiness" },
      { id: "b", text: "Chair" },
      { id: "c", text: "Justice" },
      { id: "d", text: "Flower" },
    ],
    correctOptionId: ["a", "c"],
    explanation: "Happiness, Justice",
  },
  {
    id: 395,
    quizId: 40,
    type: "multiple_choice",
    text: "Which of the following is/are countable nouns? Select all that apply.",
    options: [
      { id: "a", text: "Water" },
      { id: "b", text: "Book" },
      { id: "c", text: "Furniture" },
      { id: "d", text: "Rice" },
    ],
    correctOptionId: ["b", "c"],
    explanation: "Book, Furniture",
  },
  {
    id: 396,
    quizId: 40,
    type: "multiple_choice",
    text: "Which of the following is/are uncountable nouns? Select all that apply.",
    options: [
      { id: "a", text: "Chairs" },
      { id: "b", text: "Sugar" },
      { id: "c", text: "Cats" },
      { id: "d", text: "Tables" },
    ],
    correctOptionId: ["b"],
    explanation: "Sugar",
  },
  {
    id: 397,
    quizId: 40,
    type: "multiple_choice",
    text: "Which of the following is/are abstract nouns? Select all that apply.",
    options: [
      { id: "a", text: "Mountain" },
      { id: "b", text: "Happiness" },
      { id: "c", text: "River" },
      { id: "d", text: "Love" },
    ],
    correctOptionId: ["b", "d"],
    explanation: "Happiness, Love",
  },
  {
    id: 398,
    quizId: 40,
    type: "multiple_choice",
    text: "Which of the following is/are collective nouns? Select all that apply.",
    options: [
      { id: "a", text: "Family" },
      { id: "b", text: "Dog" },
      { id: "c", text: "Team" },
      { id: "d", text: "Furniture" },
    ],
    correctOptionId: ["a", "c"],
    explanation: "Family, Team",
  },
  {
    id: 399,
    quizId: 40,
    type: "multiple_choice",
    text: "Which of the following is/are uncountable nouns? Select all that apply.",
    options: [
      { id: "a", text: "Cat" },
      { id: "b", text: "Air" },
      { id: "c", text: "Love" },
      { id: "d", text: "Furniture" },
    ],
    correctOptionId: ["b", "c"],
    explanation: "Air, Love",
  },
  {
    id: 400,
    quizId: 40,
    type: "multiple_choice",
    text: "Which of the following is/are concrete nouns? Select all that apply.",
    options: [
      { id: "a", text: "Friendship" },
      { id: "b", text: "Chair" },
      { id: "c", text: "Love" },
      { id: "d", text: "Air" },
    ],
    correctOptionId: ["b"],
    explanation: "Chair",
  },
];
