export const presentContinuous2 = [
  {
    id: 51,
    quizId: 6,
    text: "I ____ pasta for lunch.",
    options: [
      { id: "a", text: "are cooking" },
      { id: "b", text: "is cooking" },
      { id: "c", text: "am cooking" },
    ],
    correctOptionId: "c",
    explanation: "'I' is a singular subject, so we use 'am cooking.'",
  },
  {
    id: 52,
    quizId: 6,
    text: "She ____ her favorite song right now.",
    options: [
      { id: "a", text: "are singing" },
      { id: "b", text: "is singing" },
      { id: "c", text: "am singing" },
    ],
    correctOptionId: "b",
    explanation: "'She' is a singular subject, so we use 'is singing.'",
  },
  {
    id: 53,
    quizId: 6,
    text: "They ____ a movie tonight.",
    options: [
      { id: "a", text: "are watching" },
      { id: "b", text: "is watching" },
      { id: "c", text: "am watching" },
    ],
    correctOptionId: "a",
    explanation: "'They' is a plural subject, so we use 'are watching.'",
  },
  {
    id: 54,
    quizId: 6,
    text: "My dog ____ in the garden.",
    options: [
      { id: "a", text: "are playing" },
      { id: "b", text: "is playing" },
      { id: "c", text: "am playing" },
    ],
    correctOptionId: "b",
    explanation: "'My dog' is a singular subject, so we use 'is playing.'",
  },
  {
    id: 55,
    quizId: 6,
    text: "We ____ at the new restaurant tonight.",
    options: [
      { id: "a", text: "are dining" },
      { id: "b", text: "is dining" },
      { id: "c", text: "am dining" },
    ],
    correctOptionId: "a",
    explanation: "'We' is a plural subject, so we use 'are dining.'",
  },
  {
    id: 56,
    quizId: 6,
    text: "He ____ his homework after school.",
    options: [
      { id: "a", text: "are doing" },
      { id: "b", text: "is doing" },
      { id: "c", text: "am doing" },
    ],
    correctOptionId: "b",
    explanation: "'He' is a singular subject, so we use 'is doing.'",
  },
  {
    id: 57,
    quizId: 6,
    text: "You ____ your keys on the table.",
    options: [
      { id: "a", text: "are leaving" },
      { id: "b", text: "is leaving" },
      { id: "c", text: "am leaving" },
    ],
    correctOptionId: "c",
    explanation: "'You' is a singular subject, so we use 'am leaving.'",
  },
  {
    id: 58,
    quizId: 6,
    text: "The students ____ in the classroom.",
    options: [
      { id: "a", text: "are studying" },
      { id: "b", text: "is studying" },
      { id: "c", text: "am studying" },
    ],
    correctOptionId: "a",
    explanation:
      "'The students' is a plural subject, so we use 'are studying.'",
  },
  {
    id: 59,
    quizId: 6,
    text: "She ____ a delicious cake for the party.",
    options: [
      { id: "a", text: "are baking" },
      { id: "b", text: "is baking" },
      { id: "c", text: "am baking" },
    ],
    correctOptionId: "b",
    explanation: "'She' is a singular subject, so we use 'is baking.'",
  },
  {
    id: 60,
    quizId: 6,
    text: "The baby ____ sleeping now.",
    options: [
      { id: "a", text: "are sleeping" },
      { id: "b", text: "is sleeping" },
      { id: "c", text: "am sleeping" },
    ],
    correctOptionId: "b",
    explanation: "'The baby' is a singular subject.  Sub/ is / verb+ing .'",
  },
];
