export const presentContinuous3 = [
  {
    id: 61,
    quizId: 7,
    text: "What ____ they doing at the moment?",
    options: [
      { id: "a", text: "is" },
      { id: "b", text: "are" },
      { id: "c", text: "am" },
    ],
    correctOptionId: "b",
    explanation: "We use 'are' in interrogative sentences for 'they.'",
  },
  {
    id: 62,
    quizId: 7,
    text: "The children ____ playing in the park now.",
    options: [
      { id: "a", text: "am not" },
      { id: "b", text: "is not" },
      { id: "c", text: "are not" },
    ],
    correctOptionId: "c",
    explanation: "We use 'are not' for negative sentences with 'the children.'",
  },
  {
    id: 63,
    quizId: 7,
    text: "____ I bothering you?",
    options: [
      { id: "a", text: "Is" },
      { id: "b", text: "Are" },
      { id: "c", text: "Am" },
    ],
    correctOptionId: "a",
    explanation: "We use 'Is' in interrogative sentences for 'I.'",
  },
  {
    id: 64,
    quizId: 7,
    text: "She ____ working late tonight.",
    options: [
      { id: "a", text: "isn't" },
      { id: "b", text: "aren't" },
      { id: "c", text: "am not" },
    ],
    correctOptionId: "a",
    explanation: "We use 'isn't' for negative sentences with 'she.'",
  },
  {
    id: 65,
    quizId: 7,
    text: "____ you reading a book right now?",
    options: [
      { id: "a", text: "Is" },
      { id: "b", text: "Are" },
      { id: "c", text: "Am" },
    ],
    correctOptionId: "b",
    explanation: "We use 'Are' in interrogative sentences for 'you.'",
  },
  {
    id: 66,
    quizId: 7,
    text: "We ____ watching a movie.",
    options: [
      { id: "a", text: "is" },
      { id: "b", text: "am" },
      { id: "c", text: "are" },
    ],
    correctOptionId: "c",
    explanation: "We use 'are' for positive sentences with 'we.'",
  },
  {
    id: 67,
    quizId: 7,
    text: "They ____ listening to music.",
    options: [
      { id: "a", text: "is" },
      { id: "b", text: "am" },
      { id: "c", text: "are" },
    ],
    correctOptionId: "c",
    explanation: "We use 'are' for positive sentences with 'they.'",
  },
  {
    id: 68,
    quizId: 7,
    text: "I ____ not working on this project.",
    options: [
      { id: "a", text: "is" },
      { id: "b", text: "am" },
      { id: "c", text: "are" },
    ],
    correctOptionId: "b",
    explanation: "We use 'am' for negative sentences with 'I.'",
  },
  {
    id: 69,
    quizId: 7,
    text: "____ Emma coming to the party tonight?",
    options: [
      { id: "a", text: "Isn't" },
      { id: "b", text: "Aren't" },
      { id: "c", text: "Doesn't" },
    ],
    correctOptionId: "a",
    explanation: "'is' is used with singular subject.",
  },
  {
    id: 70,
    quizId: 7,
    text: "The cat ____ chasing its tail.",
    options: [
      { id: "a", text: "is" },
      { id: "b", text: "am" },
      { id: "c", text: "are" },
    ],
    correctOptionId: "a",
    explanation: "We use 'is' for positive sentences with 'the cat.'",
  },
];
